# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

- stage: Test
  displayName: Test code
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarQubePrepare@4
      inputs:
        scannerMode: 'CLI'
        configMode: 'manual'
        SonarQube: 'ARO SonarQube'
        cliProjectKey: 'dummy-nodejs-master'
        cliProjectName: 'dummy-nodejs-master'
        cliSources: '.'
    - task: SonarQubeAnalyze@4
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build the image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push the image
      inputs:
        containerRegistry: 'Azure Container Registry'
        repository: 'dummy-nodejs'
        command: 'push'

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'ARO Cluster - Dev'
        version: '4.5'
        cmd: 'oc get nodes'